"""created match model

Revision ID: 379d56e490ec
Revises: c469c1df20d9
Create Date: 2026-07-15 11:33:12.115045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379d56e490ec'
down_revision = 'c469c1df20d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('match_time', sa.Time(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.tid'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.tid'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['team.tid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
